# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Build

on:
  push:
    branches:
      - bugfix-*
      - enhancement-*
      - feature-*
      - workaround-*
      - dev
      - unstable
      - master

jobs:

  #=====================================================================================================================
  # Setup
  #=====================================================================================================================

  # Node 0
  setup-demikernel0:
    name: Node 0 / Setup
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_A }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            git checkout master
            git pull
            git checkout --detach $GITHUB_SHA

  # Node 1
  setup-demikernel1:
    name: Node 1 / Setup
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_B }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            git checkout master
            git pull
            git checkout --detach $GITHUB_SHA

  #=====================================================================================================================
  # Check Formatting
  #=====================================================================================================================

  # Node 0
  check-fmt-demikernel0:
    name: Node 0 / Check Formatting
    needs: [setup-demikernel0]
    runs-on: ubuntu-latest
    steps:
      - name: Check Formatting
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_A }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make check-fmt

  # Node 1
  check-fmt-demikernel1:
    name: Node 1 / Check Formatting
    needs: [setup-demikernel1]
    runs-on: ubuntu-latest
    steps:
      - name: Check Formatting
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_B }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make check-fmt

  #=====================================================================================================================
  # Compile Debug
  #=====================================================================================================================

  # Node 0
  build-debug-demikernel0:
    name: Node 0 / Compile Debug
    needs: [check-fmt-demikernel0]
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_A }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make all DEBUG=yes

  # Node 1
  build-debug-demikernel1:
    name: Node 1 / Compile Debug
    needs: [check-fmt-demikernel1]
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_B }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make all DEBUG=yes

  #=====================================================================================================================
  # Compile Release
  #=====================================================================================================================

  # Node 0
  build-release-demikernel0:
    name: Node 0 / Compile Release
    needs: [build-debug-demikernel0]
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_A }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make all DEBUG=no

  # Node 1
  build-release-demikernel1:
    name: Node 1 / Compile Release
    needs: [build-debug-demikernel1]
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_B }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make all DEBUG=no

  #=====================================================================================================================
  # Cleanup
  #=====================================================================================================================

  # Node 0
  cleanup-demikernel0:
    name: Node 0 / Cleanup
    if: always()
    needs: [build-release-demikernel0]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_A }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make clean
            git clean -fdx
            git checkout master
            git remote prune origin

  # Node 1
  cleanup-demikernel1:
    name: Node 1 / Cleanup
    if: always()
    needs: [build-release-demikernel1]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CATNAP_HOSTNAME_B }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORTNUM }}
          envs: GITHUB_REPOSITORY,GITHUB_SHA
          script: |
            cd $GITHUB_REPOSITORY
            make clean
            git clean -fdx
            git checkout master
            git remote prune origin
